name: Action CI

on: [pull_request]

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
        run: echo Hello world
  build:
    runs-on: ubuntu-latest
    steps:
       uses: actions/checkout@v4
       uses: actions/setup-dotnet@v4
       with:
        dotnet-version: '8.0.3'
       run: dotnet build
  test:
    runs-on: ubuntu-latest
    steps:
       uses: actions/checkout@v4
       uses: actions/setup-dotnet@v4
       with:
        dotnet-version: '8.0.3'
       run: dotnet test
  publish:
    runs-on: ubuntu-latest
    steps:
       uses: actions/checkout@v4
       uses: actions/setup-dotnet@v4
       with:
        dotnet-version: '8.0.3'
       run: dotnet publish